/**
 * Payslip labels, per language.
 *
 * This is the ONLY backend i18n in the project, and it is deliberately scoped
 * to the document. Everything else the API emits — validation messages, error
 * text — is still hardcoded English reaching the UI through
 * extractErrorMessage. Widening this into a general backend i18n layer is a
 * separate piece of work; when it happens, this file is the natural seam and
 * the payroll-run reason codes (NO_BASE_SALARY etc.) are the pattern for
 * anything the client should translate itself.
 *
 * The Hindi, Gujarati and Marathi wordings were written without a native
 * speaker's review, like the app's own locale files. Corrections from a speaker
 * are expected rather than defects.
 */
const LABELS = {
  en: {
    documentTitle: 'Salary slip',
    title: 'Salary slip',
    employee: 'Employee',
    employeeCode: 'Employee code',
    role: 'Role',
    branch: 'Branch',
    phone: 'Phone',
    joined: 'Date of joining',
    reference: 'Payslip ref',
    generatedOn: 'Generated on',
    status: 'Status',
    draft: 'Draft',
    finalized: 'Final',
    gross: 'Gross pay',
    deductions: 'Deductions',
    net: 'Net pay',
    attendance: 'Attendance this month',
    item: 'Item',
    dayCount: 'Days',
    workingDays: 'Working days in month',
    workingDaysShort: 'working days',
    present: 'Days present',
    halfDays: 'Half days',
    leave: 'Days on leave (unpaid)',
    absent: 'Days absent',
    weeklyOff: 'Weekly offs (paid)',
    holidays: 'Holidays (paid)',
    pending: 'Days remaining this month',
    earnings: 'Earnings and deductions',
    description: 'Description',
    amount: 'Amount',
    basicProRated: 'Basic salary (pro-rated)',
    noBreakdown:
      'A detailed day-by-day breakdown is not available for payslips generated before this version.',
    monthInProgress:
      'This month is still in progress. Days not yet worked are excluded and the figures will change.',
    weekOffNote: 'Weekly offs and holidays are paid: they are excluded from the working-day divisor.',
    computerGenerated: 'Computer-generated payslip — no signature required.',
  },
  hi: {
    documentTitle: 'वेतन पर्ची',
    title: 'वेतन पर्ची',
    employee: 'कर्मचारी',
    employeeCode: 'कर्मचारी कोड',
    role: 'पद',
    branch: 'शाखा',
    phone: 'फ़ोन',
    joined: 'कार्यग्रहण तिथि',
    reference: 'पर्ची संख्या',
    generatedOn: 'बनाई गई',
    status: 'स्थिति',
    draft: 'प्रारूप',
    finalized: 'अंतिम',
    gross: 'कुल वेतन',
    deductions: 'कटौती',
    net: 'शुद्ध वेतन',
    attendance: 'इस महीने की उपस्थिति',
    item: 'विवरण',
    dayCount: 'दिन',
    workingDays: 'महीने के कार्यदिवस',
    workingDaysShort: 'कार्यदिवस',
    present: 'उपस्थित दिन',
    halfDays: 'आधे दिन',
    leave: 'अवकाश के दिन (अवैतनिक)',
    absent: 'अनुपस्थित दिन',
    weeklyOff: 'साप्ताहिक अवकाश (सवेतन)',
    holidays: 'छुट्टियाँ (सवेतन)',
    pending: 'इस महीने के शेष दिन',
    earnings: 'आय और कटौती',
    description: 'विवरण',
    amount: 'राशि',
    basicProRated: 'मूल वेतन (आनुपातिक)',
    noBreakdown: 'इस संस्करण से पहले बनी पर्चियों के लिए दिनवार विवरण उपलब्ध नहीं है।',
    monthInProgress: 'यह महीना अभी चल रहा है। शेष दिन शामिल नहीं हैं और आँकड़े बदल सकते हैं।',
    weekOffNote: 'साप्ताहिक अवकाश और छुट्टियाँ सवेतन हैं: इन्हें कार्यदिवसों की गणना से बाहर रखा गया है।',
    computerGenerated: 'कंप्यूटर से बनी पर्ची — हस्ताक्षर आवश्यक नहीं।',
  },
  gu: {
    documentTitle: 'પગાર પત્રક',
    title: 'પગાર પત્રક',
    employee: 'કર્મચારી',
    employeeCode: 'કર્મચારી કોડ',
    role: 'હોદ્દો',
    branch: 'શાખા',
    phone: 'ફોન',
    joined: 'જોડાયાની તારીખ',
    reference: 'પત્રક ક્રમાંક',
    generatedOn: 'બનાવ્યું',
    status: 'સ્થિતિ',
    draft: 'ડ્રાફ્ટ',
    finalized: 'આખરી',
    gross: 'કુલ પગાર',
    deductions: 'કપાત',
    net: 'ચોખ્ખો પગાર',
    attendance: 'આ મહિનાની હાજરી',
    item: 'વિગત',
    dayCount: 'દિવસ',
    workingDays: 'મહિનાના કામકાજના દિવસો',
    workingDaysShort: 'કામકાજના દિવસો',
    present: 'હાજર દિવસો',
    halfDays: 'અડધા દિવસ',
    leave: 'રજાના દિવસો (વેતન વિના)',
    absent: 'ગેરહાજર દિવસો',
    weeklyOff: 'સાપ્તાહિક રજા (વેતન સહિત)',
    holidays: 'તહેવારની રજા (વેતન સહિત)',
    pending: 'આ મહિનાના બાકી દિવસો',
    earnings: 'આવક અને કપાત',
    description: 'વિગત',
    amount: 'રકમ',
    basicProRated: 'મૂળ પગાર (પ્રમાણસર)',
    noBreakdown: 'આ સંસ્કરણ પહેલાં બનેલા પત્રકો માટે દિવસવાર વિગત ઉપલબ્ધ નથી.',
    monthInProgress: 'આ મહિનો હજુ ચાલુ છે. બાકીના દિવસો ગણ્યા નથી અને આંકડા બદલાશે.',
    weekOffNote: 'સાપ્તાહિક રજા અને તહેવારો વેતન સહિત છે: તે કામકાજના દિવસોની ગણતરીમાંથી બાકાત છે.',
    computerGenerated: 'કમ્પ્યુટરથી બનેલું પત્રક — સહીની જરૂર નથી.',
  },
  mr: {
    documentTitle: 'वेतन पत्रक',
    title: 'वेतन पत्रक',
    employee: 'कर्मचारी',
    employeeCode: 'कर्मचारी कोड',
    role: 'पद',
    branch: 'शाखा',
    phone: 'फोन',
    joined: 'रुजू झाल्याची तारीख',
    reference: 'पत्रक क्रमांक',
    generatedOn: 'तयार केले',
    status: 'स्थिती',
    draft: 'मसुदा',
    finalized: 'अंतिम',
    gross: 'एकूण वेतन',
    deductions: 'कपात',
    net: 'निव्वळ वेतन',
    attendance: 'या महिन्याची उपस्थिती',
    item: 'तपशील',
    dayCount: 'दिवस',
    workingDays: 'महिन्यातील कामाचे दिवस',
    workingDaysShort: 'कामाचे दिवस',
    present: 'उपस्थित दिवस',
    halfDays: 'अर्धे दिवस',
    leave: 'रजेचे दिवस (बिनपगारी)',
    absent: 'गैरहजर दिवस',
    weeklyOff: 'साप्ताहिक सुट्टी (पगारी)',
    holidays: 'सण-सुट्ट्या (पगारी)',
    pending: 'या महिन्यातील उरलेले दिवस',
    earnings: 'उत्पन्न आणि कपात',
    description: 'तपशील',
    amount: 'रक्कम',
    basicProRated: 'मूळ वेतन (प्रमाणशीर)',
    noBreakdown: 'या आवृत्तीपूर्वी तयार झालेल्या पत्रकांसाठी दिवसनिहाय तपशील उपलब्ध नाही.',
    monthInProgress: 'हा महिना अजून सुरू आहे. उरलेले दिवस धरलेले नाहीत आणि आकडे बदलतील.',
    weekOffNote: 'साप्ताहिक सुट्ट्या आणि सण पगारी आहेत: ते कामाच्या दिवसांच्या हिशेबातून वगळले आहेत.',
    computerGenerated: 'संगणकाने तयार केलेले पत्रक — सहीची आवश्यकता नाही.',
  },
};

const SUPPORTED = Object.keys(LABELS);

function labelsFor(lang) {
  return LABELS[lang] || LABELS.en;
}

module.exports = { LABELS, SUPPORTED, labelsFor };
