const { withGradleProperties } = require('@expo/config-plugins');

/**
 * Build only the CPU architectures you are actually installing onto.
 *
 * React Native's default is all four — `armeabi-v7a,arm64-v8a,x86,x86_64` — and
 * every one of them is packaged into the APK. On this project that is **127MB of
 * native libraries in a 147MB debug APK**, of which a modern phone runs exactly
 * one set:
 *
 *     arm64-v8a     38.8 MB   <- the only ABI a Galaxy S24 reports
 *     x86           34.4 MB
 *     x86_64        33.3 MB
 *     armeabi-v7a   20.6 MB
 *
 * So ~88MB of every install was native code the device cannot execute. That is
 * not merely wasteful: `npm run android` pushes the APK over `adb install`, and
 * on a **wireless** adb connection a transfer that size is long enough to be
 * interrupted. When it is, Expo reports `adb.exe: failed to install … exited with
 * non-zero code: 1` and swallows adb's own message, so the failure reads like a
 * build problem rather than a dropped socket. Cutting the payload is the fix that
 * makes the install reliable rather than retried.
 *
 * It also cuts build time, because Gradle stops compiling and packaging three
 * architectures nobody asked for.
 *
 * ## Why a config plugin and not a line in android/gradle.properties
 *
 * `android/` is generated by `expo prebuild` and edits inside it are silently
 * discarded on the next run — see CLAUDE.md. `withGradleProperties` writes the
 * same property as part of prebuild, so it survives.
 *
 * ## The one thing to know before shipping
 *
 * The default here is **arm64-v8a only**, which is right for a development build
 * on a modern phone and wrong for two other cases:
 *
 *  - an **emulator**, which is usually `x86_64`;
 *  - a **release APK for distribution**, where dropping `armeabi-v7a` excludes
 *    every 32-bit device still in use.
 *
 * Both are handled by the environment variable rather than by editing this file,
 * so a one-off build never turns into a committed change:
 *
 *     EXPO_ANDROID_ARCHITECTURES=x86_64 npm run android
 *     EXPO_ANDROID_ARCHITECTURES=arm64-v8a,armeabi-v7a npx expo prebuild
 *
 * Read as a member expression, not destructured: `frontend/.env` values are
 * rewritten by Expo's Babel transform and this one is not, but keeping the same
 * shape everywhere is what stops the two being confused.
 */
const DEFAULT_ARCHITECTURES = 'arm64-v8a';

module.exports = function withAndroidArchitectures(config, { architectures } = {}) {
  const value =
    process.env.EXPO_ANDROID_ARCHITECTURES || architectures || DEFAULT_ARCHITECTURES;

  return withGradleProperties(config, (cfg) => {
    // Replace rather than append: gradle.properties already ships the property
    // with all four ABIs, and a duplicate key would leave the last one winning
    // by accident rather than by intent.
    cfg.modResults = cfg.modResults.filter(
      (item) => !(item.type === 'property' && item.key === 'reactNativeArchitectures')
    );
    cfg.modResults.push({
      type: 'comment',
      value: 'Set by plugins/withAndroidArchitectures.js — override with EXPO_ANDROID_ARCHITECTURES.',
    });
    cfg.modResults.push({
      type: 'property',
      key: 'reactNativeArchitectures',
      value,
    });
    return cfg;
  });
};
